os:
- Visual Studio 2017

platform:
- x64

configuration:
- Debug
- Release

branches:
  except:
  - gh-pages

artifacts:
- path: build\**.lib

before_build:
- git submodule update --init --recursive

build_script:
- mkdir build
- cd build
- cmake .. -G "Visual Studio 15 2017" -DLIBWIRE_TESTS=ON -DLIBWIRE_EXAMPLES=ON
- cmake --build . --config %CONFIGURATION%

test_script:
- cmake --build . --config %CONFIGURATION% --target check

